const products=[
 {name:'Handwoven Bengal Tant',type:'Cotton · Bengal',price:3490,tag:'Handwoven',class:'p1'},
 {name:'Lal Paar Heritage Saree',type:'Cotton · Bengal',price:4290,old:4990,tag:'Authentic',class:'p2'},
 {name:'Tussar Silk, Kora',type:'Silk · Bhagalpur',price:6890,tag:'Handpicked',class:'p3'},
 {name:'Jamdani, Maroon Bloom',type:'Cotton · Bengal',price:5490,tag:'Handwoven',class:'p4'}
];
let bag=[];let wish=0;const money=n=>'₹'+n.toLocaleString('en-IN');
document.querySelector('#productGrid').innerHTML=products.map((p,i)=>`<article class="product-card"><div class="product-image ${p.class}"><span class="badge">${p.tag}</span><button class="heart" data-wish="${i}" aria-label="Add to wishlist">♡</button><div class="quick"><button data-add="${i}">Quick add</button></div></div><div class="product-info"><div><h3>${p.name}</h3><span>★★★★★</span></div><p>${p.type}</p><b>${money(p.price)}${p.old?` <del>${money(p.old)}</del>`:''}</b></div></article>`).join('');
const drawer=document.querySelector('#bagDrawer'),overlay=document.querySelector('#overlay'),toast=document.querySelector('#toast');
function drawBag(){const items=document.querySelector('#bagItems');document.querySelector('#bagCount').textContent=bag.length;document.querySelector('#bagLabel').textContent=`(${bag.length})`;document.querySelector('#subtotal').textContent=money(bag.reduce((s,p)=>s+p.price,0));items.innerHTML=bag.length?bag.map((p,i)=>`<div class="bag-item"><div class="bag-thumb"></div><div><h4>${p.name}</h4><p>${p.type}</p><b>${money(p.price)}</b></div><button data-remove="${i}">×</button></div>`).join(''):'<p>Your bag is waiting for a story.</p>';}
function add(i){bag.push(products[i]);drawBag();showToast(`${products[i].name} added to your bag`)}function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
document.addEventListener('click',e=>{const add=e.target.dataset.add,wi=e.target.dataset.wish,remove=e.target.dataset.remove;if(add!==undefined)addProduct(add);if(wi!==undefined){e.target.classList.toggle('liked');wish+=e.target.classList.contains('liked')?1:-1;document.querySelector('#wishCount').textContent=wish;showToast(e.target.classList.contains('liked')?'Saved to your wishlist':'Removed from wishlist')}if(remove!==undefined){bag.splice(remove,1);drawBag()}});function addProduct(i){add(i)}
document.querySelector('#bagBtn').onclick=()=>{drawer.classList.add('open');overlay.classList.add('show')};document.querySelectorAll('.close,#overlay').forEach(e=>e.onclick=()=>{drawer.classList.remove('open');overlay.classList.remove('show');document.querySelector('#searchModal').classList.remove('open')});
document.querySelector('#searchBtn').onclick=()=>document.querySelector('#searchModal').classList.add('open');document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();showToast('You’re woven into the Oitijhyo story.');e.target.reset()};window.addEventListener('scroll',()=>document.querySelector('#topbar').classList.toggle('compact',scrollY>70));
