import { useEffect, useState } from 'react';
import logo from '../assets/oitijhyo-logo-source.jpeg';
import hero from '../assets/oitijhyo-hero.png';

const products = [
  { name: 'Handwoven Bengal Tant', type: 'Cotton · Bengal', price: 3490, tag: 'Handwoven', imageClass: 'p1' },
  { name: 'Lal Paar Heritage Saree', type: 'Cotton · Bengal', price: 4290, old: 4990, tag: 'Authentic', imageClass: 'p2' },
  { name: 'Tussar Silk, Kora', type: 'Silk · Bhagalpur', price: 6890, tag: 'Handpicked', imageClass: 'p3' },
  { name: 'Jamdani, Maroon Bloom', type: 'Cotton · Bengal', price: 5490, tag: 'Handwoven', imageClass: 'p4' },
];
const money = (value) => `₹${value.toLocaleString('en-IN')}`;
const Brand = () => <a className="brand logo-brand" href="#home" aria-label="Oitijhyo home"><span className="logo-window"><img src={logo} alt="Oitijhyo Saree Boutique logo" /></span></a>;
const Heading = ({ eyebrow, children, action }) => <div className="section-head"><div><p className="eyebrow">{eyebrow}</p><h2>{children}</h2></div>{action}</div>;

export default function App() {
  const [bag, setBag] = useState([]);
  const [wishlist, setWishlist] = useState([]);
  const [bagOpen, setBagOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [toast, setToast] = useState('');
  const [compact, setCompact] = useState(false);

  useEffect(() => { const scroll = () => setCompact(window.scrollY > 70); window.addEventListener('scroll', scroll); return () => window.removeEventListener('scroll', scroll); }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 2400); return () => clearTimeout(timer); }, [toast]);
  const add = (item) => { setBag((current) => [...current, item]); setToast(`${item.name} added to your bag`); };
  const toggleWish = (item) => { const exists = wishlist.some(({ name }) => name === item.name); setWishlist((current) => exists ? current.filter(({ name }) => name !== item.name) : [...current, item]); setToast(exists ? 'Removed from your wishlist' : 'Saved to your wishlist'); };
  const closePanels = () => { setBagOpen(false); setSearchOpen(false); };
  const subtotal = bag.reduce((total, item) => total + item.price, 0);

  return <>
    <div className="announcement"><span>Authentic Indian Sarees</span><i /><span>Handpicked with Heritage</span><i /><span>Complimentary shipping over ₹2,000</span></div>
    <header id="topbar" className={compact ? 'compact' : ''}><button className="mobile-menu" aria-label="Open menu">☰</button><Brand /><nav><a className="active" href="#home">Home</a><a href="#collections">Shop</a><a href="#collections">Collections</a><a href="#story">Our Story</a><a href="#craft">Craft & Heritage</a><a href="#journal">Journal</a></nav><div className="nav-tools"><button onClick={() => setSearchOpen(true)} aria-label="Search">⌕</button><button aria-label="Account">♙</button><button aria-label="Wishlist">♡<b>{wishlist.length}</b></button><button onClick={() => setBagOpen(true)} aria-label="Shopping bag">▱<b>{bag.length}</b></button></div></header>
    <main id="home">
      <section className="hero"><img src={hero} alt="Woman wearing an ivory Bengal saree with a maroon border" /><div className="hero-shade" /><div className="hero-copy"><p className="eyebrow light">A modern expression of heritage</p><h1>Tradition,<br /><em>Woven Beautifully.</em></h1><p>Discover authentic sarees rooted in India's rich textile heritage, thoughtfully curated for the modern woman.</p><div className="actions"><a className="btn primary" href="#bestsellers">Explore Collection <span>→</span></a><a className="text-link light" href="#story">Discover our story <span>↗</span></a></div></div><div className="hero-note"><span>01 — 04</span><span>Scroll to discover</span></div></section>
      <section className="intro"><p className="eyebrow">An ode to the hands that make</p><h2>Sarees with a sense<br />of <em>place.</em></h2><p className="intro-copy">We seek out the quiet beauty of Indian weaving traditions — pieces shaped by time, place, and the hands that know them best.</p><a className="text-link" href="#story">More about Oitijhyo <span>→</span></a></section>
      <Collections />
      <section className="products" id="bestsellers"><Heading eyebrow="Most considered pieces" action={<div className="product-nav"><button aria-label="Previous products">←</button><button aria-label="Next products">→</button></div>}>Loved by <em>Her</em></Heading><div className="product-grid">{products.map((item) => <article className="product-card" key={item.name}><div className={`product-image ${item.imageClass}`}><span className="badge">{item.tag}</span><button onClick={() => toggleWish(item)} className={`heart ${wishlist.some(({ name }) => name === item.name) ? 'liked' : ''}`} aria-label={`Add ${item.name} to wishlist`}>♡</button><div className="quick"><button onClick={() => add(item)}>Quick add</button></div></div><div className="product-info"><div><h3>{item.name}</h3><span>★★★★★</span></div><p>{item.type}</p><b>{money(item.price)} {item.old && <del>{money(item.old)}</del>}</b></div></article>)}</div></section>
      <Story />
      <section className="craft" id="craft"><p className="eyebrow">Made by hands. Passed through generations.</p><h2>Craft worth<br /><em>keeping close.</em></h2><div className="stats">{[[<>50<sup>+</sup></>, 'Artisan families'], [<>100<sup>%</sup></>, 'Handpicked pieces'], [<>6<sup>+</sup></>, 'Craft traditions'], ['Every piece', 'With a story']].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><small>Demo values — designed to be updated with verified sourcing information.</small></section>
      <Values /><Journal />
      <section className="newsletter"><div><p className="eyebrow light">A note in your inbox</p><h2>Stay woven into<br />our <em>story.</em></h2></div><form onSubmit={(event) => { event.preventDefault(); setToast('You’re woven into the Oitijhyo story.'); event.currentTarget.reset(); }}><label htmlFor="email">New collections, stories from artisans, and a little bit of Bengal.</label><div><input id="email" type="email" required placeholder="Your email address" /><button className="btn primary">Join Oitijhyo <span>→</span></button></div></form></section>
    </main>
    <Footer />
    <aside className={`drawer ${bagOpen ? 'open' : ''}`} aria-hidden={!bagOpen}><div className="drawer-head"><h3>Your Bag <small>({bag.length})</small></h3><button onClick={closePanels} className="close" aria-label="Close bag">×</button></div><div className="bag-items">{bag.length ? bag.map((item, index) => <div className="bag-item" key={`${item.name}-${index}`}><div className="bag-thumb" /><div><h4>{item.name}</h4><p>{item.type}</p><b>{money(item.price)}</b></div><button onClick={() => setBag((current) => current.filter((_, position) => position !== index))} aria-label={`Remove ${item.name}`}>×</button></div>) : <p>Your bag is waiting for a story.</p>}</div><div className="drawer-foot"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><button className="btn dark">Proceed to checkout <span>→</span></button></div></aside>
    <div id="overlay" className={bagOpen ? 'show' : ''} onClick={closePanels} />
    <div className={`search-modal ${searchOpen ? 'open' : ''}`}><button onClick={closePanels} className="close" aria-label="Close search">×</button><p className="eyebrow">Find your saree</p><input autoFocus={searchOpen} placeholder="Try ‘Bengal cotton’ or ‘red saree’" /><div><span>Popular searches</span><button>Bengal cotton</button><button>Festive edit</button><button>Jamdani</button></div></div>
    <div id="toast" className={toast ? 'show' : ''}>{toast}</div>
  </>;
}

function Collections() { const cards = [['01', <>Bengal<br />Collection</>, 'Woven close to home', 'one'], ['02', 'Jamdani', 'Poetry in every thread', 'two'], ['03', <>Festive<br />Edit</>, 'For days worth remembering', 'three']]; return <section className="collections" id="collections"><Heading eyebrow="Curated from the loom" action={<a className="text-link" href="#bestsellers">View all collections <span>→</span></a>}>Threads of <em>Heritage</em></Heading><div className="collection-grid">{cards.map(([number, title, copy, className]) => <a className={`collection ${className}`} href="#bestsellers" key={number}><div><span>{number}</span><h3>{title}</h3><p>{copy}</p><b>Explore <em>→</em></b></div></a>)}</div></section>; }
function Story() { return <section className="story" id="story"><div className="story-img"><div className="weave-pattern" /><div className="story-card"><p>Stories carried<br />from one generation<br />to the next.</p><span>Oitijhyo, 2026</span></div></div><div className="story-copy"><p className="eyebrow">The Oitijhyo way</p><h2>Every saree<br />has a <em>story.</em></h2><p>Oitijhyo is a passage between the people who make and those who choose to wear. We celebrate regional craftsmanship, traditional weaving techniques, and the rich cultural vocabulary of every thread.</p><p>Our collections are thoughtfully assembled to let artistry speak — honestly, beautifully, and without hurry.</p><a className="btn dark" href="#craft">Discover our craft <span>→</span></a></div></section>; }
function Values() { const values = [['01', 'Authenticity', 'Thoughtfully sourced and carefully described — so you can know the hands and heritage behind your saree.'], ['02', 'Craftsmanship', 'Honouring India’s weaving communities and the slow, skilled practices that make each textile distinct.'], ['03', 'Heritage', 'Preserving stories passed down through generations, one extraordinary weave at a time.'], ['04', 'Conscious Luxury', 'Fashion that values people, culture, material and the lasting beauty of things made well.']]; return <section className="values">{values.map(([number, title, copy]) => <div key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></div>)}</section>; }
function Journal() { const stories = [['j1', 'Craft Notes · 6 min read', 'The story behind the Bengali Tant saree'], ['j2', 'Heritage · 4 min read', 'Jamdani: a craft woven like poetry'], ['j3', 'Guide · 5 min read', 'How to identify an authentic handloom saree']]; return <section className="journal" id="journal"><Heading eyebrow="From our journal" action={<a className="text-link" href="#journal">Read the journal <span>→</span></a>}>Notes from the <em>loom.</em></Heading><div className="journal-grid">{stories.map(([image, meta, title]) => <article key={title}><div className={`journal-img ${image}`} /><p>{meta}</p><h3>{title}</h3><a href="#journal">Read story →</a></article>)}</div></section>; }
function Footer() { return <footer><div className="footer-top"><Brand /><p>Woven with tradition.<br />Made for today.</p><div className="footer-links"><div><b>Shop</b><a href="#bestsellers">New arrivals</a><a href="#bestsellers">Best sellers</a><a href="#collections">Bengal collection</a><a href="#collections">Silk sarees</a></div><div><b>About</b><a href="#story">Our story</a><a href="#craft">Craft & heritage</a><a href="#journal">Journal</a><a href="#home">Contact</a></div><div><b>Follow</b><a href="#home">Instagram</a><a href="#home">Pinterest</a><a href="#home">Facebook</a></div></div></div><div className="footer-bottom"><span>© 2026 Oitijhyo. All rights reserved.</span><span>India / INR</span><span>Privacy & terms</span></div></footer>; }
